version: '3.1'

services:
  mysqlbd:
    image: mysql:5.7.26
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sunshine
      MYSQL_ROOT_PASSWORD: tAJRd21_Dx
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - ./docker/mysql:/var/lib/mysql
